# Site settings
title: Sireesha Kolli, MD, MPH
email:
description: > # this means to ignore newlines until "baseurl:"
  Sireesha Kolli is a child, adolescent and adult psychiatrist
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kollimd.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
